# © Andrew Wei

version: 2
jobs:
  build:
    working_directory: ~/mathjax-dom
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Publish to NPM
          command: |
            if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" >> ~/.npmrc
              npm publish
              echo "Successfully published to NPM"
            else
              echo "Skipping publish because this is not a release"
            fi